protocols = imap lmtp

listen = *

mail_location = maildir:/var/mail/%d/%n/Maildir

mail_uid = 5000
mail_gid = 5000

auth_mechanisms = plain login

disable_plaintext_auth = yes

ssl = required

ssl_cert = </etc/dovecot/certs/fullchain.pem
ssl_key = </etc/dovecot/certs/privkey.pem

passdb sql {
    driver = sql
    args = /etc/dovecot/dovecot-sql.conf.ext
}

userdb sql {
    driver = sql
    args = /etc/dovecot/dovecot-sql.conf.ext
}

service imap-login {
    inet_listener imap {
        port = 143
    }

    inet_listener imaps {
        port = 993
        ssl = yes
    }
}

service lmtp {
    inet_listener lmtp {
        address = 0.0.0.0
        port = 24
    }
}

service auth {
    inet_listener {
        address = 0.0.0.0
        port = 12345
    }

    user = root
}

service auth-worker {
}

protocol lmtp {
    postmaster_address = postmaster@lab.ir

    mail_plugins = $mail_plugins
}

protocol imap {
}

namespace inbox {
    inbox = yes
}

protocol doveadm {
}
